### PR TITLE
bike data source has a bad SSL certificate right now, causing wget to fail

### PR DESCRIPTION
**Pull request by minrk**
skip certificate check in postBuild in order to allow download

Includes `set -e`, which is needed for failed download to fail the build, instead

Test this branch [here](https://mybinder.org/v2/gh/minrk/explore-open-data/bad-cert)

### CODE REVIEW

**Comment by willingc** [comment]
@betatim Works for me.

**Comment by betatim** [comment]
Thanks for finding this. Must be new because it used to work?

**Comment by minrk** [comment]
It doesn't *look* like the certificate is new, but I'm not sure. It's also possible that the certificate itself is unchanged, but they've (accidentally) stopped serving an intermediate certificate. You can see this, for instance, if you are using letsencrypt and serve `cert.pem` (only your cert) instead of `fullchain.pem` (your cert and an intermediate).

**Comment by DonGoginho** [comment]
Thx @betatim and @minrk for your Feedback. Indeed, we've changed our hoster two days ago. So it's really possible that there's a problem. I've contacted our developpers if they could check where the problem is. We'll keep you informed about their feedback. 

Interesting is why @willingc hasn't the same problem as you @minrk ... what's the difference?

**Comment by willingc** [comment]
To clarify @DonGoginho. I was reviewing @minrk's PR and that was what worked. It did not work for me prior to the PR.

**Comment by minrk** [comment]
For where it works and where it doesn't likely has to do with what certificates and certificate authorities are trusted. Interestingly, on my machine `curl` (provided by the system) works and `wget` (built by homebrew) doesn't:

macOS 10.12.6 (16G29)

curl provided by the OS:

```
$ which curl
/usr/bin/curl
$ curl --version
curl 7.54.0 (x86_64-apple-darwin16.0) libcurl/7.54.0 SecureTransport zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets
```

and wget from homebrew:

```
$ which wget
/usr/local/bin/wget
$ wget --version
GNU Wget 1.19.2 built on darwin16.7.0.

-cares +digest -gpgme +https +ipv6 -iri +large-file -metalink -nls
+ntlm +opie -psl +ssl/openssl

Wgetrc:
    /usr/local/etc/wgetrc (system)
Compile:
    clang -DHAVE_CONFIG_H -DSYSTEM_WGETRC="/usr/local/etc/wgetrc"
    -DLOCALEDIR="/usr/local/Cellar/wget/1.19.2/share/locale" -I.
    -I../lib -I../lib -I/usr/local/opt/openssl@1.1/include -DNDEBUG
Link:
    clang -DNDEBUG -L/usr/local/opt/openssl@1.1/lib -lssl -lcrypto -ldl
    -lz ftp-opie.o openssl.o http-ntlm.o ../lib/libgnu.a -liconv

Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later
<http://www.gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Originally written by Hrvoje Niksic <hniksic@xemacs.org>.
Please send bug reports and questions to <bug-wget@gnu.org>.
```

**Comment by DonGoginho** [comment]
Thx @minrk and @willingc, I‘ll foreward your feedback and get back to you when I know more. +1

**Comment by metaodi** [comment]
fyi: we just fixed the SSL issue on data.stadt-zuerich.ch, i.e. the intermediate certificate was missing, now it's there and the certificate error should be gone. I tested your original `wget` command and didn't get any error. cc @DonGoginho

**Comment by betatim** [comment]
Super! @metaodi you want to make a PR to remove the options to `wget`? Also thanks a lot for working on this in the evening!

Otherwise I will get to this tomorrow as well as the python side downloads.

**Comment by DonGoginho** [comment]
Thx @metaodi, awesome 💪

**Pull request merged**
